### ISSUE TITLE
BUG: Back button navigates to the home page, rather than the previous page

### ISSUE THREAD

**Issue by KyleADay** [bin-nuance-bat/project#263]
## DESCRIPTION

**Steps to reproduce:** 
- Navigate to the `/scanitem` or `/editsnack` page
- Click the back button

**Expected behaviour:** 
- The back button should return to the previous page

**Observed behaviour:** 
- The back button returns the user to the home page

**Comment by Brownie956** [comment]
The app allows the user to buy an 'UNKNOWN'. It then falls over when you try and send a slack reminder.
Steps to reproduce:
- Use an item that isn't recognised or, when asked to allow access to the camera, click no
- Then on the `/editsnack` page, click back.
- The page will say is this an 'Unknown'. Click yes
- Try and send a slack message. BUG - The application falls over

**Comment by Brownie956** [comment]
When asked to allow access to the camera, if you click 'don't allow', then the user is taken to the /editsnack page. However they get stuck on this page because clicking back takes them to the /scanitem page which ultimately takes them back to the /editsnack page. The only way for the user to get back to home is to go through the whole process
