### ISSUE TITLE
There is no 'give up' indication when connection fails

### ISSUE THREAD

**Issue by HelloUniverseNo31415** [bin-nuance-bat/project#275]
## DESCRIPTION

**Steps to reproduce:** 
- Experience a connection loss for a few minutes

**Expected behaviour:** 
- UNKNOWN - maybe there shouldn't be a limit, or the user should get a notification to try again later

**Observed behaviour:** 
- The calls are retried 10 times and then stopped however the app still tells the user it is retrying

**Comment by Brownie956** [comment]
- If the connection drops **after** the user had loaded the page, then when the user is taken to the error page, the 'connection lost' notification **is not** removed (see screenshot).
- If the connection drops **before** the user has loaded the page (I.E if I was to navigate to the home page after the connection has dropped), the 'connection lost' notification **is** removed.
- The redirection to the error page has only been applied to the home page. Other pages will still sit with the 'connection lost' notification indefinitely. All pages should redirect to the error page after connection timeout it met.
- It's a little odd to redirect the user to `/error`. Usually when a user is taken to a custom error page, the url remains unchanged. That way when the user refreshes, they attempting to retry loading the page they were on rather than simply reloading the error page. `/error` should not exist in the url and the url should remain as the url where the user has the error. (Example: https://github.com/sdfdsfvvvervdfsdsf)

![error-page](https://user-images.githubusercontent.com/11007335/44032393-ded2ee3c-9efe-11e8-88cb-da3ec75e113b.PNG)

**Comment by isaac-lapworth** [comment]
Currently we are showing the notification when connection is lost, and we are showing the error page when a request fails.

Got a few questions about your points:
 - If a request fails because of connection dropping, would it not be correct in that scenario to show the "connection lost" notification on the error page?
- How did you manage to reach the home page after connection had dropped? Was it cached?

I'd like to suggest taking the user to the error page when a request fails once, they then click to restart the flow. Spamming the same request 9 more times will rarely work better. 

I also think managing a lost connection should be separate to a failed request. They're two different scenarios.

**Comment by Brownie956** [comment]
- Completely agree that we should manage connection errors and request failures. In reality, if the user's connection drops, then the native browser should handle it.

- Combining the error page with the connection error notification is a little odd. The page reads 'please try again', and the notification says that it's already 'retrying'.

- It's not completely useless retrying requests, although maybe 10 retry attempts is excessive. Maybe something like 3 would be more suitable. 

- The page probably was cached when I was testing it. I was also using my local environment which isn't representative of how it would work in reality. If the user had a connection issue before even loading up the application then the browser native functionality would handle it.

Going forward, I think we should discuss this in a refinement session

**Comment by isaac-lapworth** [comment]
Sounds good. 
I agree that it would be good to sort the details out first. Have put in a commit to this PR (331) that removes all the different types of errors that were in state and simplifies things a fair bit. 

Currently:
 - redirecting straight to the error page when a request fails - happy to add some retries but ideally not with a first-class function as before
 - showing the connection lost when offline, not doing anything else with it yet
